# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
    build:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - run: npm install --force
            - run: npm update
            - run:
                name: install-snyk-code-test-report #custom script to convert Snyk json output into an HTML report
                command: curl https://raw.githubusercontent.com/adamsnyk/snyk-code-test-handler/master/code_test_report/__main__.py > code_test_report.py
            - snyk/scan: #container scan with manifest files
                fail-on-issues: false
                monitor-on-build: true
                token-variable: SNYK_TOKEN
                additional-arguments: --container amitsnyk/snyk-juice-shop:latest --app-vulns #replace amitsnyk/snyk-juice-shop:latest with your image name.
            - snyk/scan: #code scan with json output
                fail-on-issues: false
                monitor-on-build: false
                token-variable: SNYK_TOKEN
                additional-arguments: --code --json > output.json
            - store_artifacts: #store json output generated by snyk
                path: output.json
                destination: output.json
            - run: #use custom script to convert json output to HTML
                name: run-code-report
                command: cat output.json | python3 code_test_report.py
            - store_artifacts: #store HTML output from custom script
                path: output.html
                destination: output.html
            - run: #remove the custom script
                name: remove-run-code-report
                command: rm code_test_report.py
        workflows: null
