# Configure SNYK_TOKEN environment variable in your TravisCI project settings

language: node_js

node_js:
- node

script:
    - npm install -g snyk
    - snyk monitor --all-projects # Autodetect al projects in working directory, scan and publish results to Snyk
    - snyk test --all-projects # Autodetect all projects in working directory
